### ISSUE TITLE
Contao 4

### ISSUE THREAD

**Issue by swinde** [wiphi/contao-dielosungen#1]
Hallo ich habe einen Kunden wo ich so etwas hier gebrauchen könnte.
Soll ich mal einen Pull request für ein Bundel erstellen?

**Comment by wiphi** [comment]
Brauchst du nicht, ich bin da schon drüber ;) Danke für die Erinnerung, das wollte ich ja mal fertig machen.

**Comment by wiphi** [comment]
@swinde, ich habe gerade eine Beta-version für das Contao 4 Modul hoch gestellt. Wenn du magst, kannst du es ja einmal testen: `composer require wiphi/contao-dielosungen:2.0.0-beta`. Die Maske für das Hochladen der Losungs-XML ist noch nicht schick, aber sonst sollte alles gehen. Da ich derzeit noch keinen richtigen Anwendungsfall für das Contao 4er Modul habe, bin ich auf dein Feedback angewiesen ;)

**Comment by swinde** [comment]
Würde ich gern aber die Php-Version stimmt so nicht oder besser geschrieben habe ich 7.1 und Composer bricht ab.
edit:
[InvalidArgumentException]
  Package wiphi/contao-dielosungen at version 2.0.0-beta has a PHP requirement incompatible with your PHP version (7.1.10.0)
Ich glaube >=7.0 wäre richtig!

**Comment by swinde** [comment]
"php":">=5.6"|">=7.0",

**Comment by wiphi** [comment]
Sorry mein Fehler, das Version-Constraint für PHP sagt das alle PHP Versionen ab 7.0 gehen bis zur nächsten Major-Version. Ich hab das ja mit der Tilde (~) geschlüsselt.
Der Fehler liegt in meinem require Ausdruck im letzten Post: `composer require wiphi/contao-dielosungen:2.0.0-beta1` Ich hab das Release ..-beta**1** genannt.

Ich habs auch gerade nochmal getestet, ich hab PHP7.1 auch im Einsatz und es läuft. Den Contao Manager teste ich auch gleich noch.

**Comment by wiphi** [comment]
Also mit dem Contao-Manager funktioniert es auch. Ich hab allerdings beides mit einer Contao version 4.5.3 am laufen. Sollte aber auch genau so gut mit einer 4.4er LTS laufen.

**Comment by swinde** [comment]
Funktioniert alles 1A!

**Comment by wiphi** [comment]
Ich habe soeben die Version 2.0.0 offiziell freigegeben. Viel Spaß mit der Erweiterung unter Contao 4.
