### ISSUE TITLE
Fehler und defektes Frontend, wenn keine Losungen importiert.

### ISSUE THREAD

**Issue by swinde** [wiphi/contao-dielosungen#2]
Hallo! Ich habe die Erweiterung jetzt fast ein Jahr in Betrieb und hatte vergessen die Losungen für das neue Jahr zu importieren. Ergebnis war eine nicht erreichbare Webseite mit folgender Fehlermeldung.

> [2019-01-06 12:33:52] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function row() on null" at /var/virtual/schule-naundorf/public/vendor/wiphi/contao-dielosungen/src/Resources/contao/modules/ModuleDieLosung.php line 65 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function row() on null at /var/virtual/schule-naundorf/public/vendor/wiphi/contao-dielosungen/src/Resources/contao/modules/ModuleDieLosung.php:65)"} []

Könnte man da eine Überprüfung einbauen ob Losungen vorhanden sind und evtl. einen kurzen Text einblenden?

Meine Contao Version 4.6.12

**Comment by wiphi** [comment]
Danke fürs Melden! 
Ich habe eine Bugfix Version bereitgestellt. In dieser ist das Problem behoben.
