### ISSUE TITLE
Zeitzone

### ISSUE THREAD

**Issue by ChristianKaMe** [wiphi/contao-dielosungen#3]
Moin,
Die Losungen werden bei mir (Contao4.6*) nur angezeigt, wenn die Zeitzone GMT eingestellt sind.
Bei allen anderen Einstellungen ist nichts zu sehen. Gibt es eine Möglichkeit, das zu ändern?
Beste Grüße
Christian

**Comment by wiphi** [comment]
Bitte prüfe, ob der Fehler auch auftritt, wenn du die Losungen unter Zeitzone importiertst. Ich vermute, du hast erst die Losungen importiert und anschließend die Zeitzone geändert?

**Comment by ChristianKaMe** [comment]
Danke! Das war des Rätsels Lösung!

VG Christian

 

Von: Philipp Winkel <notifications@github.com> 
Gesendet: Dienstag, 26. März 2019 13:19
An: wiphi/contao-dielosungen <contao-dielosungen@noreply.github.com>
Cc: ChristianKaMe <christian.mellin@gmx.net>; Author <author@noreply.github.com>
Betreff: Re: [wiphi/contao-dielosungen] Zeitzone (#3)

 

Bitte prüfe, ob der Fehler auch auftritt, wenn du die Losungen unter Zeitzone importiertst. Ich vermute, du hast erst die Losungen importiert und anschließend die Zeitzone geändert?
