### ISSUE TITLE
PHP 8.1 und Contao 4.13

### ISSUE THREAD

**Issue by swinde** [wiphi/contao-dielosungen#4]
Hallo, wird das Modul noch betreut?

Bei meinem Kunden steht der Wechsel auf PHP 8.1 und Contao 4.13 an.

Vg Steffen Winde

**Comment by wiphi** [comment]
Hallo, ist nach wie vor im Einsatz und wird auch noch gepflegt. Bis jetzt war noch kein Anwendungsfall für die neue Contao / php-Version gegeben. Das rüste ich natürlich gerne auf. Beste Grüße!

**Comment by swinde** [comment]
Vielen Dank.

**Comment by wiphi** [comment]
In Version 2.1.0 ist das Modul Contao 4.13 und PHP8 kompatibel. Schönes Wochenende :)
