### ISSUE TITLE
Contao 5

### ISSUE THREAD

**Issue by meRitAton17** [wiphi/contao-dielosungen#5]
Ich habe versucht, das Modul für contao5 zu installieren und bin gescheitert. Gibt es für contao5 / mate eine Installationsmöglichkeit?

**Comment by wiphi** [comment]
Hallo @meRitAton17,
derzeit hapert es etwas an der Zeit das Modul für Contao 5 fit zu machen. Spätestens zur ersten LTS Version von Contao 5 wird es die entsprechenden Anpassungen geben, dass das Modul auch auf Contao 5 läuft.

**Comment by meRitAton17** [comment]
Hallo wiphi, ich warte geduldig. Bitte schicke mir eine Nachricht, wenn es fertig ist. Herzliche Grüße

**Comment by wiphi** [comment]
Release 2.2.0 mit Contao 5.3 Supprt steht zur Verfügung.
